### PR TITLE
commit task 5 with GIT TAG and updated README file

### PR DESCRIPTION
**Pull request by SmithNazar**
image

### CODE REVIEW

**Comment by andrii-s-shpitser-lpnu-ua** [comment]
You did not push the TAG

**Comment by SmithNazar** [comment]
sorry, my bad

**Review by andrii-s-shpitser-lpnu-ua — APPROVED** [review]

**Comment by SmithNazar** [comment]
And one question, can I build a projects that recieves MIDI device(it's like piano keybord that allows u too control synthesizer) messages instead of implementing AI?

**Comment by andrii-s-shpitser-lpnu-ua** [comment]
What is MIDI device?

**Pull request merged**
